### ISSUE TITLE
Migrate enNZ locale

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#160]
Migrate [`enNZ` locale](https://github.com/date-fns/date-fns/tree/master/src/locale/enNZ) to TypeScript.

**Comment by Liam-Tait** [comment]
Claiming this issue

**Comment by Liam-Tait** [comment]
Above link is incorrect, correct link is [`en-NZ` locale](https://github.com/date-fns/date-fns/tree/master/src/locale/en-NZ)

**Comment by Liam-Tait** [comment]
I went to do this but it is already migrated https://github.com/date-fns/date-fns/pull/2496, so yay 🎆
