### ISSUE TITLE
Migrate eachDayOfInterval function

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#21]
Migrate [`eachDayOfInterval` function](https://github.com/date-fns/date-fns/tree/master/src/eachDayOfInterval) to TypeScript.

**Comment by mprovenc** [comment]
I can take this one

**Comment by kossnocorp** [comment]
@mprovenc thanks! I've marked the issue as claimed.

**Comment by mprovenc** [comment]
Just submitted the PR, not sure how to add labels to it/if I have the authority to add labels?

**Comment by kossnocorp** [comment]
@mprovenc sorry I didn't realize.

**Comment by maximtop** [comment]
Closed by https://github.com/date-fns/date-fns/pull/2015
