### ISSUE TITLE
Migrate eachMonthOfInterval function

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#23]
Migrate [`eachMonthOfInterval` function](https://github.com/date-fns/date-fns/tree/master/src/eachMonthOfInterval) to TypeScript.

**Comment by minitesh** [comment]
@kossnocorp I am working on this

**Comment by minitesh** [comment]
Created PR
https://github.com/date-fns/date-fns/pull/2018
