### ISSUE TITLE
Migrate eachQuarterOfInterval function

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#24]
Migrate [`eachQuarterOfInterval` function](https://github.com/date-fns/date-fns/tree/master/src/eachQuarterOfInterval) to TypeScript.

**Comment by minitesh** [comment]
@kossnocorp I am working on this

**Comment by minitesh** [comment]
Created PR 
https://github.com/date-fns/date-fns/pull/2019
