### ISSUE TITLE
Migrate eachWeekOfInterval function

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#25]
Migrate [`eachWeekOfInterval` function](https://github.com/date-fns/date-fns/tree/master/src/eachWeekOfInterval) to TypeScript.

**Comment by minitesh** [comment]
@kossnocorp I am working on this

**Comment by minitesh** [comment]
Created PR
https://github.com/date-fns/date-fns/pull/2020

**Comment by maximtop** [comment]
Closed by https://github.com/date-fns/date-fns/pull/2020
